"""empty message

Revision ID: 541dd92a1b25
Revises: 939c07bf6a44
Create Date: 2023-03-28 07:43:25.515990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541dd92a1b25'
down_revision = '939c07bf6a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
